include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_positional_boolean_parameters
    # - avoid_print
    - avoid_redundant_argument_values
    - avoid_void_async
    - cancel_subscriptions
    - prefer_const_constructors
    - prefer_final_locals
    - sort_unnamed_constructors_first
    - unnecessary_string_interpolations
    - unnecessary_await_in_return