name: askimam
description: "Ask imam v3"

publish_to: 'none'

version: 3.0.0+50

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'logo/logo.png'
