name: askimam
description: Ask imam on Azan.kz

version: 1.19.0+34

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia: ^0.1.7
  clipboard: ^0.1.2+8
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_linkify: ^3.1.2
  flutter_sound: ^1.7.0
  google_sign_in: ^4.1.1
  intl: ^0.16.0
  intl_translation: ^0.17.7
  provider: ^4.0.5
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
#  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/masjid-0.jpg
    - images/masjid-1.jpg
    - images/masjid-2.jpg
    - images/masjid-3.jpg
    - images/algolia.png
