name: askimam
description: "Ask imam v3"

publish_to: "none"

version: 3.0.0+50

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_direction: ^0.0.7
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_linkify: ^6.0.0
  flutter_modular: ^6.3.2
  flutter_sound: ^9.2.13
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.3
  permission_handler_platform_interface: ^4.1.0
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "logo/logo.png"
