name: askimam
description: AskImam 2.0.

publish_to: 'none'

version: 2.2.0+43

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_direction: ^0.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  flutter_bloc: ^7.0.0
  flutter_linkify: ^5.0.2
  flutter_modular: ^3.1.1+1
  flutter_sound_lite: ^8.1.1
  freezed_annotation: ^0.14.1
  http: ^0.13.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  flutter_modular_test: ^1.0.1
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  mockito: ^5.0.7
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "logo/logo.png"
