name: askimam
description: Ask imam on Azan.kz

version: 1.20.0+36

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia: ^0.1.7
  clipboard: ^0.1.2+8
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_linkify: ^4.0.2
  flutter_sound: ^2.1.1
  google_sign_in: ^4.5.6
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  provider: ^4.0.5
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
#  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/masjid-0.jpg
    - images/masjid-1.jpg
    - images/masjid-2.jpg
    - images/masjid-3.jpg
    - images/algolia.png
