// Mocks generated by Mockito 5.4.4 from annotations
// in askimam/test/home/chats/bloc/unanswered_chats_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:askimam/chat/domain/model/chat.dart' as _i6;
import 'package:askimam/chat/domain/repo/chat_repository.dart' as _i3;
import 'package:askimam/common/domain/model/rejection.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOption_1<A> extends _i1.SmartFake implements _i2.Option<A> {
  _FakeOption_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Rejection, _i6.Chat>> get(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Rejection, _i6.Chat>>.value(
            _FakeEither_0<_i5.Rejection, _i6.Chat>(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Rejection, _i6.Chat>>);

  @override
  _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>> find(String? phrase) =>
      (super.noSuchMethod(
        Invocation.method(
          #find,
          [phrase],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>.value(
                _FakeEither_0<_i5.Rejection, List<_i6.Chat>>(
          this,
          Invocation.method(
            #find,
            [phrase],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>> getMy(
    int? offset,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMy,
          [
            offset,
            pageSize,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>.value(
                _FakeEither_0<_i5.Rejection, List<_i6.Chat>>(
          this,
          Invocation.method(
            #getMy,
            [
              offset,
              pageSize,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>> getPublic(
    int? offset,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublic,
          [
            offset,
            pageSize,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>.value(
                _FakeEither_0<_i5.Rejection, List<_i6.Chat>>(
          this,
          Invocation.method(
            #getPublic,
            [
              offset,
              pageSize,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>> getUnanswered(
    int? offset,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnanswered,
          [
            offset,
            pageSize,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>.value(
                _FakeEither_0<_i5.Rejection, List<_i6.Chat>>(
          this,
          Invocation.method(
            #getUnanswered,
            [
              offset,
              pageSize,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Rejection, List<_i6.Chat>>>);

  @override
  _i4.Future<_i2.Option<_i5.Rejection>> add(
    _i6.ChatType? type,
    String? subject,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            type,
            subject,
            text,
          ],
        ),
        returnValue: _i4.Future<_i2.Option<_i5.Rejection>>.value(
            _FakeOption_1<_i5.Rejection>(
          this,
          Invocation.method(
            #add,
            [
              type,
              subject,
              text,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Option<_i5.Rejection>>);

  @override
  _i4.Future<_i2.Option<_i5.Rejection>> updateSubject(
    int? id,
    String? subject,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubject,
          [
            id,
            subject,
          ],
        ),
        returnValue: _i4.Future<_i2.Option<_i5.Rejection>>.value(
            _FakeOption_1<_i5.Rejection>(
          this,
          Invocation.method(
            #updateSubject,
            [
              id,
              subject,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Option<_i5.Rejection>>);

  @override
  _i4.Future<_i2.Option<_i5.Rejection>> delete(_i6.Chat? chat) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [chat],
        ),
        returnValue: _i4.Future<_i2.Option<_i5.Rejection>>.value(
            _FakeOption_1<_i5.Rejection>(
          this,
          Invocation.method(
            #delete,
            [chat],
          ),
        )),
      ) as _i4.Future<_i2.Option<_i5.Rejection>>);

  @override
  _i4.Future<_i2.Option<_i5.Rejection>> setViewedFlag(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #setViewedFlag,
          [id],
        ),
        returnValue: _i4.Future<_i2.Option<_i5.Rejection>>.value(
            _FakeOption_1<_i5.Rejection>(
          this,
          Invocation.method(
            #setViewedFlag,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Option<_i5.Rejection>>);

  @override
  _i4.Future<_i2.Option<_i5.Rejection>> returnToUnanswered(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #returnToUnanswered,
          [id],
        ),
        returnValue: _i4.Future<_i2.Option<_i5.Rejection>>.value(
            _FakeOption_1<_i5.Rejection>(
          this,
          Invocation.method(
            #returnToUnanswered,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Option<_i5.Rejection>>);
}
