// Mocks generated by Mockito 5.0.7 from annotations
// in askimam/test/imam_ratings/bloc/imam_ratings_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:askimam/common/domain/model/rejection.dart' as _i5;
import 'package:askimam/imam_ratings/domain/model/imam_ratings_with_description.dart'
    as _i6;
import 'package:askimam/imam_ratings/domain/repo/imam_ratings_repo.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ImamRatingsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockImamRatingsRepo extends _i1.Mock implements _i3.ImamRatingsRepo {
  MockImamRatingsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Rejection, _i6.ImamRatingsWithDescription>>
      getRatings() => (super.noSuchMethod(Invocation.method(#getRatings, []),
              returnValue: Future<
                      _i2.Either<_i5.Rejection,
                          _i6.ImamRatingsWithDescription>>.value(
                  _FakeEither<_i5.Rejection, _i6.ImamRatingsWithDescription>()))
          as _i4.Future<_i2.Either<_i5.Rejection, _i6.ImamRatingsWithDescription>>);
}
