// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4mhP3ox81dtyY_BFM0NtrVbZgt3rlync',
    appId: '1:674391970261:web:4bd8aa4ddc974eeab36d5c',
    messagingSenderId: '674391970261',
    projectId: 'azan-kz-ask-imam',
    authDomain: 'azan-kz-ask-imam.firebaseapp.com',
    databaseURL: 'https://azan-kz-ask-imam.firebaseio.com',
    storageBucket: 'azan-kz-ask-imam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYEp98wrGOI5hOUai0Ih0vnw8KMVc0-8',
    appId: '1:674391970261:android:5c391d0c9195f401',
    messagingSenderId: '674391970261',
    projectId: 'azan-kz-ask-imam',
    databaseURL: 'https://azan-kz-ask-imam.firebaseio.com',
    storageBucket: 'azan-kz-ask-imam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXgEdj8_6F1Qy2akTEODR5r68Zf39dYc',
    appId: '1:674391970261:ios:b1a6b82afca1556fb36d5c',
    messagingSenderId: '674391970261',
    projectId: 'azan-kz-ask-imam',
    databaseURL: 'https://azan-kz-ask-imam.firebaseio.com',
    storageBucket: 'azan-kz-ask-imam.appspot.com',
    androidClientId: '674391970261-8qtlqq6427tk17opi802vkrh7l9407bd.apps.googleusercontent.com',
    iosClientId: '674391970261-70f0gj903p4kf27chhhimps1qpgvqmsh.apps.googleusercontent.com',
    iosBundleId: 'kz.azan.askimam',
  );
}
