// Mocks generated by Mockito 5.0.3 from annotations
// in askimam/test/home/chats/ui/widget/public_chats_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:askimam/home/chats/bloc/public_chats_bloc.dart' as _i2;
import 'package:bloc/src/bloc.dart' as _i5;
import 'package:bloc/src/transition.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakePublicChatsState extends _i1.Fake implements _i2.PublicChatsState {}

class _FakeStreamSubscription<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

/// A class which mocks [PublicChatsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPublicChatsBloc extends _i1.Mock implements _i2.PublicChatsBloc {
  MockPublicChatsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PublicChatsState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakePublicChatsState()) as _i2.PublicChatsState);
  @override
  _i3.Stream<_i2.PublicChatsState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.PublicChatsState>.empty())
          as _i3.Stream<_i2.PublicChatsState>);
  @override
  _i3.Stream<_i2.PublicChatsState> mapEventToState(
          _i2.PublicChatsEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.PublicChatsState>.empty())
          as _i3.Stream<_i2.PublicChatsState>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future.value(null),
      returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  void add(_i2.PublicChatsEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.PublicChatsEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<
      _i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>> transformEvents(
          _i3.Stream<_i2.PublicChatsEvent>? events,
          _i5.TransitionFunction<_i2.PublicChatsEvent, _i2.PublicChatsState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>>.empty())
          as _i3.Stream<
              _i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>>);
  @override
  void emit(_i2.PublicChatsState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<
      _i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>> transformTransitions(
          _i3.Stream<_i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>>?
              transitions) =>
      (super.noSuchMethod(
              Invocation.method(#transformTransitions, [transitions]),
              returnValue:
                  Stream<_i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>>.empty())
          as _i3.Stream<
              _i4.Transition<_i2.PublicChatsEvent, _i2.PublicChatsState>>);
  @override
  _i3.StreamSubscription<_i2.PublicChatsState> listen(
          void Function(_i2.PublicChatsState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription<_i2.PublicChatsState>())
          as _i3.StreamSubscription<_i2.PublicChatsState>);
  @override
  void onChange(_i4.Change<_i2.PublicChatsState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}
