// Mocks generated by Mockito 5.0.5 from annotations
// in askimam/test/home/favorites/ui/widget/favorites_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:askimam/home/favorites/bloc/favorite_bloc.dart' as _i2;
import 'package:bloc/src/bloc.dart' as _i5;
import 'package:bloc/src/transition.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeFavoriteState extends _i1.Fake implements _i2.FavoriteState {}

class _FakeStreamSubscription<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

/// A class which mocks [FavoriteBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteBloc extends _i1.Mock implements _i2.FavoriteBloc {
  MockFavoriteBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeFavoriteState()) as _i2.FavoriteState);
  @override
  _i3.Stream<_i2.FavoriteState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.FavoriteState>.empty())
          as _i3.Stream<_i2.FavoriteState>);
  @override
  _i3.Stream<_i2.FavoriteState> mapEventToState(_i2.FavoriteEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.FavoriteState>.empty())
          as _i3.Stream<_i2.FavoriteState>);
  @override
  void add(_i2.FavoriteEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.FavoriteEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>> transformEvents(
          _i3.Stream<_i2.FavoriteEvent>? events,
          _i5.TransitionFunction<_i2.FavoriteEvent, _i2.FavoriteState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue: Stream<
                  _i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>.empty())
          as _i3.Stream<_i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>);
  @override
  void emit(_i2.FavoriteState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<_i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>
      transformTransitions(
              _i3.Stream<_i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue: Stream<
                      _i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>.empty())
              as _i3
                  .Stream<_i4.Transition<_i2.FavoriteEvent, _i2.FavoriteState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(null),
      returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i2.FavoriteState> listen(
          void Function(_i2.FavoriteState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription<_i2.FavoriteState>())
          as _i3.StreamSubscription<_i2.FavoriteState>);
  @override
  void onChange(_i4.Change<_i2.FavoriteState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}
